Repository qor5/docs, pull requests merged in 2022-12, with the labels that each got.

#10 build test
  hack/build-app.sh
Labels: size/XS

#11 build test
  plantbuild/build.jsonnet
Labels: size/XS

#13 update go mod
  go.mod
  go.sum
Labels: size/M

#14 update go mod
  go.mod
  go.sum
Labels: size/M

#15 build test
  plantbuild/build.jsonnet
Labels: size/XS

#18 ssh tunnel for kubectl
  hack/build-app.sh
  hack/get-tools.sh
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/S

#19 build test
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/XS

#20 Fix page title and demo image url
  docs/advanced-functions/the-go-html-builder.html
  docs/appendix/all-demo-examples.html
  docs/basics/brand.html
  docs/basics/event-handling.html
  docs/basics/filter.html
  docs/basics/form-handling.html
  docs/basics/layout-function-and-page-injector.html
  docs/basics/listing.html
  docs/basics/manipulate-page-url-in-event-func.html
  docs/basics/menu.html
  docs/basics/notification-center.html
  docs/basics/page-func-and-event-func.html
  docs/basics/partial-refresh-with-portal.html
  docs/basics/reload-page-with-a-flash.html
  docs/basics/scope-component.html
  docs/basics/shortcut.html
  docs/basics/summary-of-event-response.html
  docs/basics/switch-pages-with-push-state.html
  docs/components-guide/composite-new-component-with-go.html
  docs/components-guide/integrate-a-heavy-vue-component.html
  docs/getting-started/one-minute-quick-start.html
  docs/index.html
  docs/presets-guide/detail-page-for-complex-object.html
  docs/presets-guide/editing-customizations.html
  docs/presets-guide/its-the-whole-house.html
  docs/presets-guide/permissions.html
  docs/search_indexes.json
  docs/vuetify-components/a-taste-of-using-vuetify-in-go.html
  docs/vuetify-components/auto-complete.html
  docs/vuetify-components/basic-inputs.html
  docs/vuetify-components/lazy-portals.html
  docs/vuetify-components/linkage-select.html
  docsrc/build/main.go
  docsrc/examples/e13_vuetify_list/page.go
  docsrc/examples/e14_vuetify_menu/page.go
  docsrc/generated/examples-generated.go
  docsrc/mux.go
Labels: size/M

#16 plantbuild: fixed build process
  hack/get-tools.sh
  plantbuild/build.jsonnet
Labels: size/S

#8 Theplant website template
  cmd/qor5/admin-template/admin/config.go
  cmd/qor5/admin-template/admin/db.go
  cmd/qor5/admin-template/admin/router.go
  cmd/qor5/admin-template/dev_env
  cmd/qor5/admin-template/docker-compose.yaml
  cmd/qor5/admin-template/main.go
  cmd/qor5/admin-template/models/post.go
  cmd/qor5/admintemplate/dev_env
  cmd/qor5/bare-template/main.go
  cmd/qor5/main.go
  cmd/qor5/website-template/admin/config.go
  cmd/qor5/website-template/admin/db.go
  cmd/qor5/website-template/admin/init_sql.go
  cmd/qor5/website-template/admin/messages.go
  cmd/qor5/website-template/admin/router.go
  cmd/qor5/website-template/dev_env
  cmd/qor5/website-template/docker-compose.yaml
  cmd/qor5/website-template/main.go
  cmd/qor5/website-template/publish/contact/index.html
  cmd/qor5/website-template/publish/index.html
  cmd/qor5/website-template/publish/pricing/index.html
  go.mod
  go.sum
Labels: size/XXL

#22 Refactor listing doc
  README.md
  docs/basics/listing.html
  docs/search_indexes.json
  docsrc/content/basics/listing.go
  docsrc/examples/example_basics/listing.go
  docsrc/generated/examples-generated.go
Labels: size/M

#23 Update README.md
  README.md
Labels: size/XS

#24 Remove wrong referenced gorm
  cmd/qor5/admin-template/admin/db.go
  cmd/qor5/website-template/admin/db.go
  go.mod
  go.sum
Labels: size/S

#25 Polish website template main func
  cmd/qor5/website-template/main.go
Labels: size/S

#26 Fix and tidy website template init sql
  cmd/qor5/website-template/admin/init_sql.go
Labels: size/S

#29 Fix brand doc demo 404
  docs/appendix/all-demo-examples.html
  docs/basics/brand.html
  docsrc/content/basics/brand.go
  docsrc/examples/e21_presents/brand.go
  docsrc/examples/e21_presents/profile.go
Labels: size/M

#27 switch to ecr-public repo
  plantbuild/build.jsonnet
  plantbuild/images.jsonnet
Labels: size/XS
