Repository qor5/docs, pull requests merged in 2023-05, with the labels that each got.

#57 upgrade go to 1.20.4
  Dockerfile
Labels: size/XS

#58 ecs auto-deployment on test
  hack/build-deploy-app.sh
Labels: size/S

#61 Update autocomplete doc
  docs/search_indexes.json
  docs/vuetify-components/auto-complete.html
  docsrc/dev.sh
  docsrc/examples/e10_vuetify_autocomplete/page.go
  docsrc/generated/g1.go
  go.mod
  go.sum
Labels: size/L
