Repository qor5/docs, pull requests merged in 2023-10, with the labels that each got.

#68 fixed compile error: UseDefaultTab is undefined.
  docsrc/examples/e00_basics/activity.go
  docsrc/examples/example_basics/worker_mock_que.go
  go.mod
  go.sum
Labels: size/L

#69 comment out replace statement in go.mod file.
  cmd/qor5/website-template/admin/config.go
  go.mod
  go.sum
Labels: size/S

#56 Add tab and searching doc
  docs/activity-log.html
  docs/advanced-functions/the-go-html-builder.html
  docs/appendix/all-demo-examples.html
  docs/basics/brand.html
  docs/basics/confirm-dialog.html
  docs/basics/event-handling.html
  docs/basics/filter.html
  docs/basics/form-handling.html
  docs/basics/i18n.html
  docs/basics/l10n.html
  docs/basics/layout-function-and-page-injector.html
  docs/basics/layout.html
  docs/basics/listing-customizations.html
  docs/basics/listing.html
  docs/basics/login.html
  docs/basics/manipulate-page-url-in-event-func.html
  docs/basics/menu.html
  docs/basics/notification-center.html
  docs/basics/page-func-and-event-func.html
  docs/basics/partial-refresh-with-portal.html
  docs/basics/reload-page-with-a-flash.html
  docs/basics/scope-component.html
  docs/basics/shortcut.html
  docs/basics/summary-of-event-response.html
  docs/basics/switch-pages-with-push-state.html
  docs/basics/worker.html
  docs/components-guide/composite-new-component-with-go.html
  docs/components-guide/integrate-a-heavy-vue-component.html
  docs/getting-started/one-minute-quick-start.html
  docs/index.html
  docs/presets-guide/detail-page-for-complex-object.html
  docs/presets-guide/editing-customizations.html
  docs/presets-guide/its-the-whole-house.html
  docs/presets-guide/permissions.html
  docs/presets-guide/role.html
  docs/search_indexes.json
  docs/seo.html
  docs/slug.html
  docs/vuetify-components/a-taste-of-using-vuetify-in-go.html
  docs/vuetify-components/auto-complete.html
  docs/vuetify-components/basic-inputs.html
  docs/vuetify-components/lazy-portals.html
  docs/vuetify-components/linkage-select.html
  docsrc/content/basics/editing-customizations.go
  docsrc/content/basics/listing-customizations.go
  docsrc/examples/e21_presents/editing.go
  docsrc/examples/e21_presents/listing.go
  docsrc/examples/example_basics/listing.go
  docsrc/generated/g1.go
  docsrc/menu.go
  docsrc/mux.go
Labels: size/XL

#59 change example db
  README.md
  docs/activity-log.html
  docs/presets-guide/its-the-whole-house.html
  docs/search_indexes.json
  docs/vuetify-components/auto-complete.html
  docsrc/dev.sh
  docsrc/docker-compose.yaml
  docsrc/examples/e00_basics/activity.go
  docsrc/examples/e10_vuetify_autocomplete/page.go
  docsrc/examples/e21_presents/listing.go
  docsrc/examples/example_basics/listing.go
  docsrc/examples/utils/db.go
  docsrc/generated/g1.go
  docsrc/server/main.go
Labels: size/L

#71 upgrade-go-to-1.21.3
  Dockerfile
Labels: size/XS

#72 fixed the issue of the publish doc's demo don't work properly
  docs/basics/publish.html
  docs/search_indexes.json
  docsrc/examples/example_basics/publish.go
  docsrc/generated/g1.go
Labels: size/S

#73 upgrade web to v1.3.1
  go.mod
  go.sum
Labels: size/XS

#74 Fix example publish editing schedule bar
  docsrc/examples/example_basics/publish.go
  go.mod
  go.sum
Labels: size/XS

#75 fixed the lazy portal doc
  docs/search_indexes.json
  docs/vuetify-components/lazy-portals.html
  docsrc/content/advanced-functions/lazy-portals-and-reload.go
Labels: size/XS

#76 generate doc for 'publish doc'
  docs/basics/publish.html
  docs/search_indexes.json
  docsrc/generated/g1.go
Labels: size/XS

#77 upgrade x
  go.mod
  go.sum
Labels: size/XS
