Repository qor5/docs, pull requests merged in 2023-03, with the labels that each got.

#36 polish permission doc
  docs/appendix/all-demo-examples.html
  docs/presets-guide/permissions.html
  docs/search_indexes.json
  docsrc/content/basics/permissions.go
  docsrc/examples/example_basics/permission.go
  docsrc/generated/examples-generated.go
Labels: size/L

#37 add favicon
  docs/assets/favicon.ico
  docsrc/assets.go
  docsrc/assets/favicon.ico
  docsrc/mux.go
Labels: size/XS

#39 Refactor homepage text
  docs/index.html
  docs/search_indexes.json
  docsrc/content/getting-started/what-is-goplaid.go
  docsrc/content/home.go
  go.mod
  go.sum
Labels: size/M

#42 add action worker doc
  docs/appendix/all-demo-examples.html
  docs/basics/worker.html
  docs/search_indexes.json
  docsrc/content/basics/worker.go
  docsrc/examples/example_basics/action_worker.go
  docsrc/examples/example_basics/action_worker_mock_que.go
  docsrc/generated/examples-generated.go
  docsrc/mux.go
Labels: size/L

#46 Revert "move all other repos' snippets to docs"
  README.md
  docs/basics/layout-function-and-page-injector.html
  docs/search_indexes.json
  docsrc/content/advanced-functions/layout-function-and-page-injector.go
  docsrc/dev.sh
  docsrc/examples/tiptap/build.sh
  docsrc/examples/tiptap/tiptap.go
  docsrc/examples/tiptap/tiptapjs.go
  docsrc/examples/tiptap/tiptapjs/.browserslistrc
  docsrc/examples/tiptap/tiptapjs/.gitignore
  docsrc/examples/tiptap/tiptapjs/README.md
  docsrc/examples/tiptap/tiptapjs/babel.config.js
  docsrc/examples/tiptap/tiptapjs/demo/index.html
  docsrc/examples/tiptap/tiptapjs/dist/tiptap.css
  docsrc/examples/tiptap/tiptapjs/dist/tiptap.umd.min.js
  docsrc/examples/tiptap/tiptapjs/jsconfig.json
  docsrc/examples/tiptap/tiptapjs/package-lock.json
  docsrc/examples/tiptap/tiptapjs/package.json
  docsrc/examples/tiptap/tiptapjs/src/editor.vue
  docsrc/examples/tiptap/tiptapjs/src/icon.vue
  docsrc/examples/tiptap/tiptapjs/src/icons/add_col_after.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/add_col_before.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/add_row_after.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/add_row_before.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/bold.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/checklist.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/code.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/code_block.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/combine_cells.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/delete_col.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/delete_row.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/delete_table.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/github.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/hr.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/image.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/italic.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/link.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/mention.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/ol.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/paragraph.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/quote.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/redo.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/remove.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/strike.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/table.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/ul.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/underline.svg
  docsrc/examples/tiptap/tiptapjs/src/icons/undo.svg
  docsrc/examples/tiptap/tiptapjs/src/main.js
  docsrc/examples/tiptap/tiptapjs/src/sass/editor.scss
  docsrc/examples/tiptap/tiptapjs/src/sass/main.scss
  docsrc/examples/tiptap/tiptapjs/src/sass/menubar.scss
  docsrc/examples/tiptap/tiptapjs/src/sass/menububble.scss
  docsrc/examples/tiptap/tiptapjs/src/sass/variables.scss
  docsrc/examples/tiptap/tiptapjs/vue.config.js
  docsrc/examples/webapi/api.go
  docsrc/generated/examples-generated.go
Labels: size/XXL

#47 generate snippets from mod
  README.md
  docsrc/dev.sh
  docsrc/generated/g1.go
  docsrc/generated/g2.go
  docsrc/generated/g3.go
  docsrc/generated/g4.go
  docsrc/generated/g5.go
Labels: size/M

#48 Add MIT license
  LICENSE
Labels: size/S

#49 Update Dockerfile due to file path change
  Dockerfile
Labels: size/XS
